name: expense_tracker
description: "Expense Tracker Flutter app scaffolded in MVVM + Cubit style"
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7+1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  another_flushbar: ^1.12.30
  google_fonts: ^8.0.2
  drift: ^2.32.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  flutter_gen_runner: ^5.10.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  line_length: 140

  integrations:
    flutter_svg: true
    rive: false
    lottie: false

  colors:
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/colors/
    - assets/images/
    - assets/branding/
